language: julia
os:
        - osx
        - linux

julia:
        - 1.6
after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'


jobs:
  include:
    - stage: "Documentation"
      julia: 1.6
      os:
          - linux
          - osx
      script:
        - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/fgerick/CartesianSphericalHarmonics.jl"))'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
